// Module: BMA
// Params: Y_5,AMA

function iS9(A) {
  let B = [
      'add',
      'and',
      'cmp',
      'cmpg',
      'cmpl',
      'const',
      'div',
      'double',
      'float',
      'goto',
      'if',
      'int',
      'long',
      'move',
      'mul',
      'neg',
      'new',
      'nop',
      'not',
      'or',
      'rem',
      'return',
      'shl',
      'shr',
      'sput',
      'sub',
      'throw',
      'ushr',
      'xor',
    ],
    Q = [
      'aget',
      'aput',
      'array',
      'check',
      'execute',
      'fill',
      'filled',
      'goto/16',
      'goto/32',
      'iget',
      'instance',
      'invoke',
      'iput',
      'monitor',
      'packed',
      'sget',
      'sparse',
    ],
    I = [
      'transient',
      'constructor',
      'abstract',
      'final',
      'synthetic',
      'public',
      'private',
      'protected',
      'static',
      'bridge',
      'system',
    ];
  return {
    name: 'Smali',
    contains: [
      { className: 'string', begin: '"', end: '"', relevance: 0 },
      A.COMMENT('#', '$', { relevance: 0 }),
      {
        className: 'keyword',
        variants: [
          { begin: '\\s*\\.end\\s[a-zA-Z0-9]*' },
          { begin: '^[ ]*\\.[a-zA-Z]*', relevance: 0 },
          { begin: '\\s:[a-zA-Z_0-9]*', relevance: 0 },
          { begin: '\\s(' + I.join('|') + ')' },
        ],
      },
      {
        className: 'built_in',
        variants: [
          { begin: '\\s(' + B.join('|') + ')\\s' },
          { begin: '\\s(' + B.join('|') + ')((-|/)[a-zA-Z0-9]+)+\\s', relevance: 10 },
          { begin: '\\s(' + Q.join('|') + ')((-|/)[a-zA-Z0-9]+)*\\s', relevance: 10 },
        ],
      },
      {
        className: 'class',
        begin: `L[^(;:
]*;`,
        relevance: 0,
      },
      { begin: '[vp][0-9]+' },
    ],
  };
}
AMA.exports = iS9;
