// Module: Ec1
// Params: _i0

Object.defineProperty(_i0, '__esModule', { value: !0 });
_i0.BAGGAGE_MAX_TOTAL_LENGTH =
  _i0.BAGGAGE_MAX_PER_NAME_VALUE_PAIRS =
  _i0.BAGGAGE_MAX_NAME_VALUE_PAIRS =
  _i0.BAGGAGE_HEADER =
  _i0.BAGGAGE_ITEMS_SEPARATOR =
  _i0.BAGGAGE_PROPERTIES_SEPARATOR =
  _i0.BAGGAGE_KEY_PAIR_SEPARATOR =
    void 0;
_i0.BAGGAGE_KEY_PAIR_SEPARATOR = '=';
_i0.BAGGAGE_PROPERTIES_SEPARATOR = ';';
_i0.BAGGAGE_ITEMS_SEPARATOR = ',';
_i0.BAGGAGE_HEADER = 'baggage';
_i0.BAGGAGE_MAX_NAME_VALUE_PAIRS = 180;
_i0.BAGGAGE_MAX_PER_NAME_VALUE_PAIRS = 4096;
_i0.BAGGAGE_MAX_TOTAL_LENGTH = 8192;
