// Module: SV1
// Params: cc8,TV2

TV2.exports = PV1;
var Q95 = 1,
  I95 = 3,
  G95 = 4,
  D95 = 5,
  Z95 = 7,
  Y95 = 8,
  W95 = 9,
  F95 = 11,
  J95 = 12,
  C95 = 13,
  X95 = 14,
  V95 = 15,
  K95 = 17,
  H95 = 18,
  z95 = 19,
  w95 = 20,
  E95 = 21,
  U95 = 22,
  N95 = 23,
  $95 = 24,
  q95 = 25,
  M95 = [
    null,
    'INDEX_SIZE_ERR',
    null,
    'HIERARCHY_REQUEST_ERR',
    'WRONG_DOCUMENT_ERR',
    'INVALID_CHARACTER_ERR',
    null,
    'NO_MODIFICATION_ALLOWED_ERR',
    'NOT_FOUND_ERR',
    'NOT_SUPPORTED_ERR',
    'INUSE_ATTRIBUTE_ERR',
    'INVALID_STATE_ERR',
    'SYNTAX_ERR',
    'INVALID_MODIFICATION_ERR',
    'NAMESPACE_ERR',
    'INVALID_ACCESS_ERR',
    null,
    'TYPE_MISMATCH_ERR',
    'SECURITY_ERR',
    'NETWORK_ERR',
    'ABORT_ERR',
    'URL_MISMATCH_ERR',
    'QUOTA_EXCEEDED_ERR',
    'TIMEOUT_ERR',
    'INVALID_NODE_TYPE_ERR',
    'DATA_CLONE_ERR',
  ],
  L95 = [
    null,
    'INDEX_SIZE_ERR (1): the index is not in the allowed range',
    null,
    'HIERARCHY_REQUEST_ERR (3): the operation would yield an incorrect nodes model',
    'WRONG_DOCUMENT_ERR (4): the object is in the wrong Document, a call to importNode is required',
    'INVALID_CHARACTER_ERR (5): the string contains invalid characters',
    null,
    'NO_MODIFICATION_ALLOWED_ERR (7): the object can not be modified',
    'NOT_FOUND_ERR (8): the object can not be found here',
    'NOT_SUPPORTED_ERR (9): this operation is not supported',
    'INUSE_ATTRIBUTE_ERR (10): setAttributeNode called on owned Attribute',
    'INVALID_STATE_ERR (11): the object is in an invalid state',
    'SYNTAX_ERR (12): the string did not match the expected pattern',
    'INVALID_MODIFICATION_ERR (13): the object can not be modified in this way',
    'NAMESPACE_ERR (14): the operation is not allowed by Namespaces in XML',
    'INVALID_ACCESS_ERR (15): the object does not support the operation or argument',
    null,
    'TYPE_MISMATCH_ERR (17): the type of the object does not match the expected type',
    'SECURITY_ERR (18): the operation is insecure',
    'NETWORK_ERR (19): a network error occurred',
    'ABORT_ERR (20): the user aborted an operation',
    'URL_MISMATCH_ERR (21): the given URL does not match another URL',
    'QUOTA_EXCEEDED_ERR (22): the quota has been exceeded',
    'TIMEOUT_ERR (23): a timeout occurred',
    'INVALID_NODE_TYPE_ERR (24): the supplied node is invalid or has an invalid ancestor for this operation',
    'DATA_CLONE_ERR (25): the object can not be cloned.',
  ],
  OV2 = {
    INDEX_SIZE_ERR: Q95,
    DOMSTRING_SIZE_ERR: 2,
    HIERARCHY_REQUEST_ERR: I95,
    WRONG_DOCUMENT_ERR: G95,
    INVALID_CHARACTER_ERR: D95,
    NO_DATA_ALLOWED_ERR: 6,
    NO_MODIFICATION_ALLOWED_ERR: Z95,
    NOT_FOUND_ERR: Y95,
    NOT_SUPPORTED_ERR: W95,
    INUSE_ATTRIBUTE_ERR: 10,
    INVALID_STATE_ERR: F95,
    SYNTAX_ERR: J95,
    INVALID_MODIFICATION_ERR: C95,
    NAMESPACE_ERR: X95,
    INVALID_ACCESS_ERR: V95,
    VALIDATION_ERR: 16,
    TYPE_MISMATCH_ERR: K95,
    SECURITY_ERR: H95,
    NETWORK_ERR: z95,
    ABORT_ERR: w95,
    URL_MISMATCH_ERR: E95,
    QUOTA_EXCEEDED_ERR: U95,
    TIMEOUT_ERR: N95,
    INVALID_NODE_TYPE_ERR: $95,
    DATA_CLONE_ERR: q95,
  };
function PV1(A) {
  (Error.call(this),
    Error.captureStackTrace(this, this.constructor),
    (this.code = A),
    (this.message = L95[A]),
    (this.name = M95[A]));
}
PV1.prototype.__proto__ = Error.prototype;
for (Ve in OV2)
  ((TV1 = { value: OV2[Ve] }),
    Object.defineProperty(PV1, Ve, TV1),
    Object.defineProperty(PV1.prototype, Ve, TV1));
var TV1, Ve;
