// Module: IA2
// Params: BA2

Object.defineProperty(BA2, '__esModule', { value: !0 });
BA2.SDK_INFO = void 0;
var Ty6 = zn0(),
  Go = wN();
BA2.SDK_INFO = {
  [Go.SEMRESATTRS_TELEMETRY_SDK_NAME]: 'opentelemetry',
  [Go.SEMRESATTRS_PROCESS_RUNTIME_NAME]: 'node',
  [Go.SEMRESATTRS_TELEMETRY_SDK_LANGUAGE]: Go.TELEMETRYSDKLANGUAGEVALUES_NODEJS,
  [Go.SEMRESATTRS_TELEMETRY_SDK_VERSION]: Ty6.VERSION,
};
