// Module: Ht0
// Params: Wt0

Object.defineProperty(Wt0, '__esModule', { value: !0 });
Wt0.SEMATTRS_NET_HOST_CARRIER_ICC =
  Wt0.SEMATTRS_NET_HOST_CARRIER_MNC =
  Wt0.SEMATTRS_NET_HOST_CARRIER_MCC =
  Wt0.SEMATTRS_NET_HOST_CARRIER_NAME =
  Wt0.SEMATTRS_NET_HOST_CONNECTION_SUBTYPE =
  Wt0.SEMATTRS_NET_HOST_CONNECTION_TYPE =
  Wt0.SEMATTRS_NET_HOST_NAME =
  Wt0.SEMATTRS_NET_HOST_PORT =
  Wt0.SEMATTRS_NET_HOST_IP =
  Wt0.SEMATTRS_NET_PEER_NAME =
  Wt0.SEMATTRS_NET_PEER_PORT =
  Wt0.SEMATTRS_NET_PEER_IP =
  Wt0.SEMATTRS_NET_TRANSPORT =
  Wt0.SEMATTRS_FAAS_INVOKED_REGION =
  Wt0.SEMATTRS_FAAS_INVOKED_PROVIDER =
  Wt0.SEMATTRS_FAAS_INVOKED_NAME =
  Wt0.SEMATTRS_FAAS_COLDSTART =
  Wt0.SEMATTRS_FAAS_CRON =
  Wt0.SEMATTRS_FAAS_TIME =
  Wt0.SEMATTRS_FAAS_DOCUMENT_NAME =
  Wt0.SEMATTRS_FAAS_DOCUMENT_TIME =
  Wt0.SEMATTRS_FAAS_DOCUMENT_OPERATION =
  Wt0.SEMATTRS_FAAS_DOCUMENT_COLLECTION =
  Wt0.SEMATTRS_FAAS_EXECUTION =
  Wt0.SEMATTRS_FAAS_TRIGGER =
  Wt0.SEMATTRS_EXCEPTION_ESCAPED =
  Wt0.SEMATTRS_EXCEPTION_STACKTRACE =
  Wt0.SEMATTRS_EXCEPTION_MESSAGE =
  Wt0.SEMATTRS_EXCEPTION_TYPE =
  Wt0.SEMATTRS_DB_SQL_TABLE =
  Wt0.SEMATTRS_DB_MONGODB_COLLECTION =
  Wt0.SEMATTRS_DB_REDIS_DATABASE_INDEX =
  Wt0.SEMATTRS_DB_HBASE_NAMESPACE =
  Wt0.SEMATTRS_DB_CASSANDRA_COORDINATOR_DC =
  Wt0.SEMATTRS_DB_CASSANDRA_COORDINATOR_ID =
  Wt0.SEMATTRS_DB_CASSANDRA_SPECULATIVE_EXECUTION_COUNT =
  Wt0.SEMATTRS_DB_CASSANDRA_IDEMPOTENCE =
  Wt0.SEMATTRS_DB_CASSANDRA_TABLE =
  Wt0.SEMATTRS_DB_CASSANDRA_CONSISTENCY_LEVEL =
  Wt0.SEMATTRS_DB_CASSANDRA_PAGE_SIZE =
  Wt0.SEMATTRS_DB_CASSANDRA_KEYSPACE =
  Wt0.SEMATTRS_DB_MSSQL_INSTANCE_NAME =
  Wt0.SEMATTRS_DB_OPERATION =
  Wt0.SEMATTRS_DB_STATEMENT =
  Wt0.SEMATTRS_DB_NAME =
  Wt0.SEMATTRS_DB_JDBC_DRIVER_CLASSNAME =
  Wt0.SEMATTRS_DB_USER =
  Wt0.SEMATTRS_DB_CONNECTION_STRING =
  Wt0.SEMATTRS_DB_SYSTEM =
  Wt0.SEMATTRS_AWS_LAMBDA_INVOKED_ARN =
    void 0;
Wt0.SEMATTRS_MESSAGING_DESTINATION_KIND =
  Wt0.SEMATTRS_MESSAGING_DESTINATION =
  Wt0.SEMATTRS_MESSAGING_SYSTEM =
  Wt0.SEMATTRS_AWS_DYNAMODB_GLOBAL_SECONDARY_INDEX_UPDATES =
  Wt0.SEMATTRS_AWS_DYNAMODB_ATTRIBUTE_DEFINITIONS =
  Wt0.SEMATTRS_AWS_DYNAMODB_SCANNED_COUNT =
  Wt0.SEMATTRS_AWS_DYNAMODB_COUNT =
  Wt0.SEMATTRS_AWS_DYNAMODB_TOTAL_SEGMENTS =
  Wt0.SEMATTRS_AWS_DYNAMODB_SEGMENT =
  Wt0.SEMATTRS_AWS_DYNAMODB_SCAN_FORWARD =
  Wt0.SEMATTRS_AWS_DYNAMODB_TABLE_COUNT =
  Wt0.SEMATTRS_AWS_DYNAMODB_EXCLUSIVE_START_TABLE =
  Wt0.SEMATTRS_AWS_DYNAMODB_LOCAL_SECONDARY_INDEXES =
  Wt0.SEMATTRS_AWS_DYNAMODB_GLOBAL_SECONDARY_INDEXES =
  Wt0.SEMATTRS_AWS_DYNAMODB_SELECT =
  Wt0.SEMATTRS_AWS_DYNAMODB_INDEX_NAME =
  Wt0.SEMATTRS_AWS_DYNAMODB_ATTRIBUTES_TO_GET =
  Wt0.SEMATTRS_AWS_DYNAMODB_LIMIT =
  Wt0.SEMATTRS_AWS_DYNAMODB_PROJECTION =
  Wt0.SEMATTRS_AWS_DYNAMODB_CONSISTENT_READ =
  Wt0.SEMATTRS_AWS_DYNAMODB_PROVISIONED_WRITE_CAPACITY =
  Wt0.SEMATTRS_AWS_DYNAMODB_PROVISIONED_READ_CAPACITY =
  Wt0.SEMATTRS_AWS_DYNAMODB_ITEM_COLLECTION_METRICS =
  Wt0.SEMATTRS_AWS_DYNAMODB_CONSUMED_CAPACITY =
  Wt0.SEMATTRS_AWS_DYNAMODB_TABLE_NAMES =
  Wt0.SEMATTRS_HTTP_CLIENT_IP =
  Wt0.SEMATTRS_HTTP_ROUTE =
  Wt0.SEMATTRS_HTTP_SERVER_NAME =
  Wt0.SEMATTRS_HTTP_RESPONSE_CONTENT_LENGTH_UNCOMPRESSED =
  Wt0.SEMATTRS_HTTP_RESPONSE_CONTENT_LENGTH =
  Wt0.SEMATTRS_HTTP_REQUEST_CONTENT_LENGTH_UNCOMPRESSED =
  Wt0.SEMATTRS_HTTP_REQUEST_CONTENT_LENGTH =
  Wt0.SEMATTRS_HTTP_USER_AGENT =
  Wt0.SEMATTRS_HTTP_FLAVOR =
  Wt0.SEMATTRS_HTTP_STATUS_CODE =
  Wt0.SEMATTRS_HTTP_SCHEME =
  Wt0.SEMATTRS_HTTP_HOST =
  Wt0.SEMATTRS_HTTP_TARGET =
  Wt0.SEMATTRS_HTTP_URL =
  Wt0.SEMATTRS_HTTP_METHOD =
  Wt0.SEMATTRS_CODE_LINENO =
  Wt0.SEMATTRS_CODE_FILEPATH =
  Wt0.SEMATTRS_CODE_NAMESPACE =
  Wt0.SEMATTRS_CODE_FUNCTION =
  Wt0.SEMATTRS_THREAD_NAME =
  Wt0.SEMATTRS_THREAD_ID =
  Wt0.SEMATTRS_ENDUSER_SCOPE =
  Wt0.SEMATTRS_ENDUSER_ROLE =
  Wt0.SEMATTRS_ENDUSER_ID =
  Wt0.SEMATTRS_PEER_SERVICE =
    void 0;
Wt0.DBSYSTEMVALUES_FILEMAKER =
  Wt0.DBSYSTEMVALUES_DERBY =
  Wt0.DBSYSTEMVALUES_FIREBIRD =
  Wt0.DBSYSTEMVALUES_ADABAS =
  Wt0.DBSYSTEMVALUES_CACHE =
  Wt0.DBSYSTEMVALUES_EDB =
  Wt0.DBSYSTEMVALUES_FIRSTSQL =
  Wt0.DBSYSTEMVALUES_INGRES =
  Wt0.DBSYSTEMVALUES_HANADB =
  Wt0.DBSYSTEMVALUES_MAXDB =
  Wt0.DBSYSTEMVALUES_PROGRESS =
  Wt0.DBSYSTEMVALUES_HSQLDB =
  Wt0.DBSYSTEMVALUES_CLOUDSCAPE =
  Wt0.DBSYSTEMVALUES_HIVE =
  Wt0.DBSYSTEMVALUES_REDSHIFT =
  Wt0.DBSYSTEMVALUES_POSTGRESQL =
  Wt0.DBSYSTEMVALUES_DB2 =
  Wt0.DBSYSTEMVALUES_ORACLE =
  Wt0.DBSYSTEMVALUES_MYSQL =
  Wt0.DBSYSTEMVALUES_MSSQL =
  Wt0.DBSYSTEMVALUES_OTHER_SQL =
  Wt0.SemanticAttributes =
  Wt0.SEMATTRS_MESSAGE_UNCOMPRESSED_SIZE =
  Wt0.SEMATTRS_MESSAGE_COMPRESSED_SIZE =
  Wt0.SEMATTRS_MESSAGE_ID =
  Wt0.SEMATTRS_MESSAGE_TYPE =
  Wt0.SEMATTRS_RPC_JSONRPC_ERROR_MESSAGE =
  Wt0.SEMATTRS_RPC_JSONRPC_ERROR_CODE =
  Wt0.SEMATTRS_RPC_JSONRPC_REQUEST_ID =
  Wt0.SEMATTRS_RPC_JSONRPC_VERSION =
  Wt0.SEMATTRS_RPC_GRPC_STATUS_CODE =
  Wt0.SEMATTRS_RPC_METHOD =
  Wt0.SEMATTRS_RPC_SERVICE =
  Wt0.SEMATTRS_RPC_SYSTEM =
  Wt0.SEMATTRS_MESSAGING_KAFKA_TOMBSTONE =
  Wt0.SEMATTRS_MESSAGING_KAFKA_PARTITION =
  Wt0.SEMATTRS_MESSAGING_KAFKA_CLIENT_ID =
  Wt0.SEMATTRS_MESSAGING_KAFKA_CONSUMER_GROUP =
  Wt0.SEMATTRS_MESSAGING_KAFKA_MESSAGE_KEY =
  Wt0.SEMATTRS_MESSAGING_RABBITMQ_ROUTING_KEY =
  Wt0.SEMATTRS_MESSAGING_CONSUMER_ID =
  Wt0.SEMATTRS_MESSAGING_OPERATION =
  Wt0.SEMATTRS_MESSAGING_MESSAGE_PAYLOAD_COMPRESSED_SIZE_BYTES =
  Wt0.SEMATTRS_MESSAGING_MESSAGE_PAYLOAD_SIZE_BYTES =
  Wt0.SEMATTRS_MESSAGING_CONVERSATION_ID =
  Wt0.SEMATTRS_MESSAGING_MESSAGE_ID =
  Wt0.SEMATTRS_MESSAGING_URL =
  Wt0.SEMATTRS_MESSAGING_PROTOCOL_VERSION =
  Wt0.SEMATTRS_MESSAGING_PROTOCOL =
  Wt0.SEMATTRS_MESSAGING_TEMP_DESTINATION =
    void 0;
Wt0.FAASINVOKEDPROVIDERVALUES_ALIBABA_CLOUD =
  Wt0.FaasDocumentOperationValues =
  Wt0.FAASDOCUMENTOPERATIONVALUES_DELETE =
  Wt0.FAASDOCUMENTOPERATIONVALUES_EDIT =
  Wt0.FAASDOCUMENTOPERATIONVALUES_INSERT =
  Wt0.FaasTriggerValues =
  Wt0.FAASTRIGGERVALUES_OTHER =
  Wt0.FAASTRIGGERVALUES_TIMER =
  Wt0.FAASTRIGGERVALUES_PUBSUB =
  Wt0.FAASTRIGGERVALUES_HTTP =
  Wt0.FAASTRIGGERVALUES_DATASOURCE =
  Wt0.DbCassandraConsistencyLevelValues =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_LOCAL_SERIAL =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_SERIAL =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_ANY =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_LOCAL_ONE =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_THREE =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_TWO =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_ONE =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_LOCAL_QUORUM =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_QUORUM =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_EACH_QUORUM =
  Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_ALL =
  Wt0.DbSystemValues =
  Wt0.DBSYSTEMVALUES_COCKROACHDB =
  Wt0.DBSYSTEMVALUES_MEMCACHED =
  Wt0.DBSYSTEMVALUES_ELASTICSEARCH =
  Wt0.DBSYSTEMVALUES_GEODE =
  Wt0.DBSYSTEMVALUES_NEO4J =
  Wt0.DBSYSTEMVALUES_DYNAMODB =
  Wt0.DBSYSTEMVALUES_COSMOSDB =
  Wt0.DBSYSTEMVALUES_COUCHDB =
  Wt0.DBSYSTEMVALUES_COUCHBASE =
  Wt0.DBSYSTEMVALUES_REDIS =
  Wt0.DBSYSTEMVALUES_MONGODB =
  Wt0.DBSYSTEMVALUES_HBASE =
  Wt0.DBSYSTEMVALUES_CASSANDRA =
  Wt0.DBSYSTEMVALUES_COLDFUSION =
  Wt0.DBSYSTEMVALUES_H2 =
  Wt0.DBSYSTEMVALUES_VERTICA =
  Wt0.DBSYSTEMVALUES_TERADATA =
  Wt0.DBSYSTEMVALUES_SYBASE =
  Wt0.DBSYSTEMVALUES_SQLITE =
  Wt0.DBSYSTEMVALUES_POINTBASE =
  Wt0.DBSYSTEMVALUES_PERVASIVE =
  Wt0.DBSYSTEMVALUES_NETEZZA =
  Wt0.DBSYSTEMVALUES_MARIADB =
  Wt0.DBSYSTEMVALUES_INTERBASE =
  Wt0.DBSYSTEMVALUES_INSTANTDB =
  Wt0.DBSYSTEMVALUES_INFORMIX =
    void 0;
Wt0.MESSAGINGOPERATIONVALUES_RECEIVE =
  Wt0.MessagingDestinationKindValues =
  Wt0.MESSAGINGDESTINATIONKINDVALUES_TOPIC =
  Wt0.MESSAGINGDESTINATIONKINDVALUES_QUEUE =
  Wt0.HttpFlavorValues =
  Wt0.HTTPFLAVORVALUES_QUIC =
  Wt0.HTTPFLAVORVALUES_SPDY =
  Wt0.HTTPFLAVORVALUES_HTTP_2_0 =
  Wt0.HTTPFLAVORVALUES_HTTP_1_1 =
  Wt0.HTTPFLAVORVALUES_HTTP_1_0 =
  Wt0.NetHostConnectionSubtypeValues =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_LTE_CA =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_NRNSA =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_NR =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_IWLAN =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_TD_SCDMA =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_GSM =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_HSPAP =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_EHRPD =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_LTE =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_EVDO_B =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_IDEN =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_HSPA =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_HSUPA =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_HSDPA =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_CDMA2000_1XRTT =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_EVDO_A =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_EVDO_0 =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_CDMA =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_UMTS =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_EDGE =
  Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_GPRS =
  Wt0.NetHostConnectionTypeValues =
  Wt0.NETHOSTCONNECTIONTYPEVALUES_UNKNOWN =
  Wt0.NETHOSTCONNECTIONTYPEVALUES_UNAVAILABLE =
  Wt0.NETHOSTCONNECTIONTYPEVALUES_CELL =
  Wt0.NETHOSTCONNECTIONTYPEVALUES_WIRED =
  Wt0.NETHOSTCONNECTIONTYPEVALUES_WIFI =
  Wt0.NetTransportValues =
  Wt0.NETTRANSPORTVALUES_OTHER =
  Wt0.NETTRANSPORTVALUES_INPROC =
  Wt0.NETTRANSPORTVALUES_PIPE =
  Wt0.NETTRANSPORTVALUES_UNIX =
  Wt0.NETTRANSPORTVALUES_IP =
  Wt0.NETTRANSPORTVALUES_IP_UDP =
  Wt0.NETTRANSPORTVALUES_IP_TCP =
  Wt0.FaasInvokedProviderValues =
  Wt0.FAASINVOKEDPROVIDERVALUES_GCP =
  Wt0.FAASINVOKEDPROVIDERVALUES_AZURE =
  Wt0.FAASINVOKEDPROVIDERVALUES_AWS =
    void 0;
Wt0.MessageTypeValues =
  Wt0.MESSAGETYPEVALUES_RECEIVED =
  Wt0.MESSAGETYPEVALUES_SENT =
  Wt0.RpcGrpcStatusCodeValues =
  Wt0.RPCGRPCSTATUSCODEVALUES_UNAUTHENTICATED =
  Wt0.RPCGRPCSTATUSCODEVALUES_DATA_LOSS =
  Wt0.RPCGRPCSTATUSCODEVALUES_UNAVAILABLE =
  Wt0.RPCGRPCSTATUSCODEVALUES_INTERNAL =
  Wt0.RPCGRPCSTATUSCODEVALUES_UNIMPLEMENTED =
  Wt0.RPCGRPCSTATUSCODEVALUES_OUT_OF_RANGE =
  Wt0.RPCGRPCSTATUSCODEVALUES_ABORTED =
  Wt0.RPCGRPCSTATUSCODEVALUES_FAILED_PRECONDITION =
  Wt0.RPCGRPCSTATUSCODEVALUES_RESOURCE_EXHAUSTED =
  Wt0.RPCGRPCSTATUSCODEVALUES_PERMISSION_DENIED =
  Wt0.RPCGRPCSTATUSCODEVALUES_ALREADY_EXISTS =
  Wt0.RPCGRPCSTATUSCODEVALUES_NOT_FOUND =
  Wt0.RPCGRPCSTATUSCODEVALUES_DEADLINE_EXCEEDED =
  Wt0.RPCGRPCSTATUSCODEVALUES_INVALID_ARGUMENT =
  Wt0.RPCGRPCSTATUSCODEVALUES_UNKNOWN =
  Wt0.RPCGRPCSTATUSCODEVALUES_CANCELLED =
  Wt0.RPCGRPCSTATUSCODEVALUES_OK =
  Wt0.MessagingOperationValues =
  Wt0.MESSAGINGOPERATIONVALUES_PROCESS =
    void 0;
var zC = Mc1(),
  Un0 = 'aws.lambda.invoked_arn',
  Nn0 = 'db.system',
  $n0 = 'db.connection_string',
  qn0 = 'db.user',
  Mn0 = 'db.jdbc.driver_classname',
  Ln0 = 'db.name',
  Rn0 = 'db.statement',
  On0 = 'db.operation',
  Tn0 = 'db.mssql.instance_name',
  Pn0 = 'db.cassandra.keyspace',
  Sn0 = 'db.cassandra.page_size',
  _n0 = 'db.cassandra.consistency_level',
  jn0 = 'db.cassandra.table',
  yn0 = 'db.cassandra.idempotence',
  kn0 = 'db.cassandra.speculative_execution_count',
  xn0 = 'db.cassandra.coordinator.id',
  fn0 = 'db.cassandra.coordinator.dc',
  vn0 = 'db.hbase.namespace',
  bn0 = 'db.redis.database_index',
  gn0 = 'db.mongodb.collection',
  hn0 = 'db.sql.table',
  mn0 = 'exception.type',
  dn0 = 'exception.message',
  un0 = 'exception.stacktrace',
  pn0 = 'exception.escaped',
  cn0 = 'faas.trigger',
  ln0 = 'faas.execution',
  in0 = 'faas.document.collection',
  nn0 = 'faas.document.operation',
  an0 = 'faas.document.time',
  sn0 = 'faas.document.name',
  rn0 = 'faas.time',
  on0 = 'faas.cron',
  tn0 = 'faas.coldstart',
  en0 = 'faas.invoked_name',
  Aa0 = 'faas.invoked_provider',
  Ba0 = 'faas.invoked_region',
  Qa0 = 'net.transport',
  Ia0 = 'net.peer.ip',
  Ga0 = 'net.peer.port',
  Da0 = 'net.peer.name',
  Za0 = 'net.host.ip',
  Ya0 = 'net.host.port',
  Wa0 = 'net.host.name',
  Fa0 = 'net.host.connection.type',
  Ja0 = 'net.host.connection.subtype',
  Ca0 = 'net.host.carrier.name',
  Xa0 = 'net.host.carrier.mcc',
  Va0 = 'net.host.carrier.mnc',
  Ka0 = 'net.host.carrier.icc',
  Ha0 = 'peer.service',
  za0 = 'enduser.id',
  wa0 = 'enduser.role',
  Ea0 = 'enduser.scope',
  Ua0 = 'thread.id',
  Na0 = 'thread.name',
  $a0 = 'code.function',
  qa0 = 'code.namespace',
  Ma0 = 'code.filepath',
  La0 = 'code.lineno',
  Ra0 = 'http.method',
  Oa0 = 'http.url',
  Ta0 = 'http.target',
  Pa0 = 'http.host',
  Sa0 = 'http.scheme',
  _a0 = 'http.status_code',
  ja0 = 'http.flavor',
  ya0 = 'http.user_agent',
  ka0 = 'http.request_content_length',
  xa0 = 'http.request_content_length_uncompressed',
  fa0 = 'http.response_content_length',
  va0 = 'http.response_content_length_uncompressed',
  ba0 = 'http.server_name',
  ga0 = 'http.route',
  ha0 = 'http.client_ip',
  ma0 = 'aws.dynamodb.table_names',
  da0 = 'aws.dynamodb.consumed_capacity',
  ua0 = 'aws.dynamodb.item_collection_metrics',
  pa0 = 'aws.dynamodb.provisioned_read_capacity',
  ca0 = 'aws.dynamodb.provisioned_write_capacity',
  la0 = 'aws.dynamodb.consistent_read',
  ia0 = 'aws.dynamodb.projection',
  na0 = 'aws.dynamodb.limit',
  aa0 = 'aws.dynamodb.attributes_to_get',
  sa0 = 'aws.dynamodb.index_name',
  ra0 = 'aws.dynamodb.select',
  oa0 = 'aws.dynamodb.global_secondary_indexes',
  ta0 = 'aws.dynamodb.local_secondary_indexes',
  ea0 = 'aws.dynamodb.exclusive_start_table',
  As0 = 'aws.dynamodb.table_count',
  Bs0 = 'aws.dynamodb.scan_forward',
  Qs0 = 'aws.dynamodb.segment',
  Is0 = 'aws.dynamodb.total_segments',
  Gs0 = 'aws.dynamodb.count',
  Ds0 = 'aws.dynamodb.scanned_count',
  Zs0 = 'aws.dynamodb.attribute_definitions',
  Ys0 = 'aws.dynamodb.global_secondary_index_updates',
  Ws0 = 'messaging.system',
  Fs0 = 'messaging.destination',
  Js0 = 'messaging.destination_kind',
  Cs0 = 'messaging.temp_destination',
  Xs0 = 'messaging.protocol',
  Vs0 = 'messaging.protocol_version',
  Ks0 = 'messaging.url',
  Hs0 = 'messaging.message_id',
  zs0 = 'messaging.conversation_id',
  ws0 = 'messaging.message_payload_size_bytes',
  Es0 = 'messaging.message_payload_compressed_size_bytes',
  Us0 = 'messaging.operation',
  Ns0 = 'messaging.consumer_id',
  $s0 = 'messaging.rabbitmq.routing_key',
  qs0 = 'messaging.kafka.message_key',
  Ms0 = 'messaging.kafka.consumer_group',
  Ls0 = 'messaging.kafka.client_id',
  Rs0 = 'messaging.kafka.partition',
  Os0 = 'messaging.kafka.tombstone',
  Ts0 = 'rpc.system',
  Ps0 = 'rpc.service',
  Ss0 = 'rpc.method',
  _s0 = 'rpc.grpc.status_code',
  js0 = 'rpc.jsonrpc.version',
  ys0 = 'rpc.jsonrpc.request_id',
  ks0 = 'rpc.jsonrpc.error_code',
  xs0 = 'rpc.jsonrpc.error_message',
  fs0 = 'message.type',
  vs0 = 'message.id',
  bs0 = 'message.compressed_size',
  gs0 = 'message.uncompressed_size';
Wt0.SEMATTRS_AWS_LAMBDA_INVOKED_ARN = Un0;
Wt0.SEMATTRS_DB_SYSTEM = Nn0;
Wt0.SEMATTRS_DB_CONNECTION_STRING = $n0;
Wt0.SEMATTRS_DB_USER = qn0;
Wt0.SEMATTRS_DB_JDBC_DRIVER_CLASSNAME = Mn0;
Wt0.SEMATTRS_DB_NAME = Ln0;
Wt0.SEMATTRS_DB_STATEMENT = Rn0;
Wt0.SEMATTRS_DB_OPERATION = On0;
Wt0.SEMATTRS_DB_MSSQL_INSTANCE_NAME = Tn0;
Wt0.SEMATTRS_DB_CASSANDRA_KEYSPACE = Pn0;
Wt0.SEMATTRS_DB_CASSANDRA_PAGE_SIZE = Sn0;
Wt0.SEMATTRS_DB_CASSANDRA_CONSISTENCY_LEVEL = _n0;
Wt0.SEMATTRS_DB_CASSANDRA_TABLE = jn0;
Wt0.SEMATTRS_DB_CASSANDRA_IDEMPOTENCE = yn0;
Wt0.SEMATTRS_DB_CASSANDRA_SPECULATIVE_EXECUTION_COUNT = kn0;
Wt0.SEMATTRS_DB_CASSANDRA_COORDINATOR_ID = xn0;
Wt0.SEMATTRS_DB_CASSANDRA_COORDINATOR_DC = fn0;
Wt0.SEMATTRS_DB_HBASE_NAMESPACE = vn0;
Wt0.SEMATTRS_DB_REDIS_DATABASE_INDEX = bn0;
Wt0.SEMATTRS_DB_MONGODB_COLLECTION = gn0;
Wt0.SEMATTRS_DB_SQL_TABLE = hn0;
Wt0.SEMATTRS_EXCEPTION_TYPE = mn0;
Wt0.SEMATTRS_EXCEPTION_MESSAGE = dn0;
Wt0.SEMATTRS_EXCEPTION_STACKTRACE = un0;
Wt0.SEMATTRS_EXCEPTION_ESCAPED = pn0;
Wt0.SEMATTRS_FAAS_TRIGGER = cn0;
Wt0.SEMATTRS_FAAS_EXECUTION = ln0;
Wt0.SEMATTRS_FAAS_DOCUMENT_COLLECTION = in0;
Wt0.SEMATTRS_FAAS_DOCUMENT_OPERATION = nn0;
Wt0.SEMATTRS_FAAS_DOCUMENT_TIME = an0;
Wt0.SEMATTRS_FAAS_DOCUMENT_NAME = sn0;
Wt0.SEMATTRS_FAAS_TIME = rn0;
Wt0.SEMATTRS_FAAS_CRON = on0;
Wt0.SEMATTRS_FAAS_COLDSTART = tn0;
Wt0.SEMATTRS_FAAS_INVOKED_NAME = en0;
Wt0.SEMATTRS_FAAS_INVOKED_PROVIDER = Aa0;
Wt0.SEMATTRS_FAAS_INVOKED_REGION = Ba0;
Wt0.SEMATTRS_NET_TRANSPORT = Qa0;
Wt0.SEMATTRS_NET_PEER_IP = Ia0;
Wt0.SEMATTRS_NET_PEER_PORT = Ga0;
Wt0.SEMATTRS_NET_PEER_NAME = Da0;
Wt0.SEMATTRS_NET_HOST_IP = Za0;
Wt0.SEMATTRS_NET_HOST_PORT = Ya0;
Wt0.SEMATTRS_NET_HOST_NAME = Wa0;
Wt0.SEMATTRS_NET_HOST_CONNECTION_TYPE = Fa0;
Wt0.SEMATTRS_NET_HOST_CONNECTION_SUBTYPE = Ja0;
Wt0.SEMATTRS_NET_HOST_CARRIER_NAME = Ca0;
Wt0.SEMATTRS_NET_HOST_CARRIER_MCC = Xa0;
Wt0.SEMATTRS_NET_HOST_CARRIER_MNC = Va0;
Wt0.SEMATTRS_NET_HOST_CARRIER_ICC = Ka0;
Wt0.SEMATTRS_PEER_SERVICE = Ha0;
Wt0.SEMATTRS_ENDUSER_ID = za0;
Wt0.SEMATTRS_ENDUSER_ROLE = wa0;
Wt0.SEMATTRS_ENDUSER_SCOPE = Ea0;
Wt0.SEMATTRS_THREAD_ID = Ua0;
Wt0.SEMATTRS_THREAD_NAME = Na0;
Wt0.SEMATTRS_CODE_FUNCTION = $a0;
Wt0.SEMATTRS_CODE_NAMESPACE = qa0;
Wt0.SEMATTRS_CODE_FILEPATH = Ma0;
Wt0.SEMATTRS_CODE_LINENO = La0;
Wt0.SEMATTRS_HTTP_METHOD = Ra0;
Wt0.SEMATTRS_HTTP_URL = Oa0;
Wt0.SEMATTRS_HTTP_TARGET = Ta0;
Wt0.SEMATTRS_HTTP_HOST = Pa0;
Wt0.SEMATTRS_HTTP_SCHEME = Sa0;
Wt0.SEMATTRS_HTTP_STATUS_CODE = _a0;
Wt0.SEMATTRS_HTTP_FLAVOR = ja0;
Wt0.SEMATTRS_HTTP_USER_AGENT = ya0;
Wt0.SEMATTRS_HTTP_REQUEST_CONTENT_LENGTH = ka0;
Wt0.SEMATTRS_HTTP_REQUEST_CONTENT_LENGTH_UNCOMPRESSED = xa0;
Wt0.SEMATTRS_HTTP_RESPONSE_CONTENT_LENGTH = fa0;
Wt0.SEMATTRS_HTTP_RESPONSE_CONTENT_LENGTH_UNCOMPRESSED = va0;
Wt0.SEMATTRS_HTTP_SERVER_NAME = ba0;
Wt0.SEMATTRS_HTTP_ROUTE = ga0;
Wt0.SEMATTRS_HTTP_CLIENT_IP = ha0;
Wt0.SEMATTRS_AWS_DYNAMODB_TABLE_NAMES = ma0;
Wt0.SEMATTRS_AWS_DYNAMODB_CONSUMED_CAPACITY = da0;
Wt0.SEMATTRS_AWS_DYNAMODB_ITEM_COLLECTION_METRICS = ua0;
Wt0.SEMATTRS_AWS_DYNAMODB_PROVISIONED_READ_CAPACITY = pa0;
Wt0.SEMATTRS_AWS_DYNAMODB_PROVISIONED_WRITE_CAPACITY = ca0;
Wt0.SEMATTRS_AWS_DYNAMODB_CONSISTENT_READ = la0;
Wt0.SEMATTRS_AWS_DYNAMODB_PROJECTION = ia0;
Wt0.SEMATTRS_AWS_DYNAMODB_LIMIT = na0;
Wt0.SEMATTRS_AWS_DYNAMODB_ATTRIBUTES_TO_GET = aa0;
Wt0.SEMATTRS_AWS_DYNAMODB_INDEX_NAME = sa0;
Wt0.SEMATTRS_AWS_DYNAMODB_SELECT = ra0;
Wt0.SEMATTRS_AWS_DYNAMODB_GLOBAL_SECONDARY_INDEXES = oa0;
Wt0.SEMATTRS_AWS_DYNAMODB_LOCAL_SECONDARY_INDEXES = ta0;
Wt0.SEMATTRS_AWS_DYNAMODB_EXCLUSIVE_START_TABLE = ea0;
Wt0.SEMATTRS_AWS_DYNAMODB_TABLE_COUNT = As0;
Wt0.SEMATTRS_AWS_DYNAMODB_SCAN_FORWARD = Bs0;
Wt0.SEMATTRS_AWS_DYNAMODB_SEGMENT = Qs0;
Wt0.SEMATTRS_AWS_DYNAMODB_TOTAL_SEGMENTS = Is0;
Wt0.SEMATTRS_AWS_DYNAMODB_COUNT = Gs0;
Wt0.SEMATTRS_AWS_DYNAMODB_SCANNED_COUNT = Ds0;
Wt0.SEMATTRS_AWS_DYNAMODB_ATTRIBUTE_DEFINITIONS = Zs0;
Wt0.SEMATTRS_AWS_DYNAMODB_GLOBAL_SECONDARY_INDEX_UPDATES = Ys0;
Wt0.SEMATTRS_MESSAGING_SYSTEM = Ws0;
Wt0.SEMATTRS_MESSAGING_DESTINATION = Fs0;
Wt0.SEMATTRS_MESSAGING_DESTINATION_KIND = Js0;
Wt0.SEMATTRS_MESSAGING_TEMP_DESTINATION = Cs0;
Wt0.SEMATTRS_MESSAGING_PROTOCOL = Xs0;
Wt0.SEMATTRS_MESSAGING_PROTOCOL_VERSION = Vs0;
Wt0.SEMATTRS_MESSAGING_URL = Ks0;
Wt0.SEMATTRS_MESSAGING_MESSAGE_ID = Hs0;
Wt0.SEMATTRS_MESSAGING_CONVERSATION_ID = zs0;
Wt0.SEMATTRS_MESSAGING_MESSAGE_PAYLOAD_SIZE_BYTES = ws0;
Wt0.SEMATTRS_MESSAGING_MESSAGE_PAYLOAD_COMPRESSED_SIZE_BYTES = Es0;
Wt0.SEMATTRS_MESSAGING_OPERATION = Us0;
Wt0.SEMATTRS_MESSAGING_CONSUMER_ID = Ns0;
Wt0.SEMATTRS_MESSAGING_RABBITMQ_ROUTING_KEY = $s0;
Wt0.SEMATTRS_MESSAGING_KAFKA_MESSAGE_KEY = qs0;
Wt0.SEMATTRS_MESSAGING_KAFKA_CONSUMER_GROUP = Ms0;
Wt0.SEMATTRS_MESSAGING_KAFKA_CLIENT_ID = Ls0;
Wt0.SEMATTRS_MESSAGING_KAFKA_PARTITION = Rs0;
Wt0.SEMATTRS_MESSAGING_KAFKA_TOMBSTONE = Os0;
Wt0.SEMATTRS_RPC_SYSTEM = Ts0;
Wt0.SEMATTRS_RPC_SERVICE = Ps0;
Wt0.SEMATTRS_RPC_METHOD = Ss0;
Wt0.SEMATTRS_RPC_GRPC_STATUS_CODE = _s0;
Wt0.SEMATTRS_RPC_JSONRPC_VERSION = js0;
Wt0.SEMATTRS_RPC_JSONRPC_REQUEST_ID = ys0;
Wt0.SEMATTRS_RPC_JSONRPC_ERROR_CODE = ks0;
Wt0.SEMATTRS_RPC_JSONRPC_ERROR_MESSAGE = xs0;
Wt0.SEMATTRS_MESSAGE_TYPE = fs0;
Wt0.SEMATTRS_MESSAGE_ID = vs0;
Wt0.SEMATTRS_MESSAGE_COMPRESSED_SIZE = bs0;
Wt0.SEMATTRS_MESSAGE_UNCOMPRESSED_SIZE = gs0;
Wt0.SemanticAttributes = zC.createConstMap([
  Un0,
  Nn0,
  $n0,
  qn0,
  Mn0,
  Ln0,
  Rn0,
  On0,
  Tn0,
  Pn0,
  Sn0,
  _n0,
  jn0,
  yn0,
  kn0,
  xn0,
  fn0,
  vn0,
  bn0,
  gn0,
  hn0,
  mn0,
  dn0,
  un0,
  pn0,
  cn0,
  ln0,
  in0,
  nn0,
  an0,
  sn0,
  rn0,
  on0,
  tn0,
  en0,
  Aa0,
  Ba0,
  Qa0,
  Ia0,
  Ga0,
  Da0,
  Za0,
  Ya0,
  Wa0,
  Fa0,
  Ja0,
  Ca0,
  Xa0,
  Va0,
  Ka0,
  Ha0,
  za0,
  wa0,
  Ea0,
  Ua0,
  Na0,
  $a0,
  qa0,
  Ma0,
  La0,
  Ra0,
  Oa0,
  Ta0,
  Pa0,
  Sa0,
  _a0,
  ja0,
  ya0,
  ka0,
  xa0,
  fa0,
  va0,
  ba0,
  ga0,
  ha0,
  ma0,
  da0,
  ua0,
  pa0,
  ca0,
  la0,
  ia0,
  na0,
  aa0,
  sa0,
  ra0,
  oa0,
  ta0,
  ea0,
  As0,
  Bs0,
  Qs0,
  Is0,
  Gs0,
  Ds0,
  Zs0,
  Ys0,
  Ws0,
  Fs0,
  Js0,
  Cs0,
  Xs0,
  Vs0,
  Ks0,
  Hs0,
  zs0,
  ws0,
  Es0,
  Us0,
  Ns0,
  $s0,
  qs0,
  Ms0,
  Ls0,
  Rs0,
  Os0,
  Ts0,
  Ps0,
  Ss0,
  _s0,
  js0,
  ys0,
  ks0,
  xs0,
  fs0,
  vs0,
  bs0,
  gs0,
]);
var hs0 = 'other_sql',
  ms0 = 'mssql',
  ds0 = 'mysql',
  us0 = 'oracle',
  ps0 = 'db2',
  cs0 = 'postgresql',
  ls0 = 'redshift',
  is0 = 'hive',
  ns0 = 'cloudscape',
  as0 = 'hsqldb',
  ss0 = 'progress',
  rs0 = 'maxdb',
  os0 = 'hanadb',
  ts0 = 'ingres',
  es0 = 'firstsql',
  Ar0 = 'edb',
  Br0 = 'cache',
  Qr0 = 'adabas',
  Ir0 = 'firebird',
  Gr0 = 'derby',
  Dr0 = 'filemaker',
  Zr0 = 'informix',
  Yr0 = 'instantdb',
  Wr0 = 'interbase',
  Fr0 = 'mariadb',
  Jr0 = 'netezza',
  Cr0 = 'pervasive',
  Xr0 = 'pointbase',
  Vr0 = 'sqlite',
  Kr0 = 'sybase',
  Hr0 = 'teradata',
  zr0 = 'vertica',
  wr0 = 'h2',
  Er0 = 'coldfusion',
  Ur0 = 'cassandra',
  Nr0 = 'hbase',
  $r0 = 'mongodb',
  qr0 = 'redis',
  Mr0 = 'couchbase',
  Lr0 = 'couchdb',
  Rr0 = 'cosmosdb',
  Or0 = 'dynamodb',
  Tr0 = 'neo4j',
  Pr0 = 'geode',
  Sr0 = 'elasticsearch',
  _r0 = 'memcached',
  jr0 = 'cockroachdb';
Wt0.DBSYSTEMVALUES_OTHER_SQL = hs0;
Wt0.DBSYSTEMVALUES_MSSQL = ms0;
Wt0.DBSYSTEMVALUES_MYSQL = ds0;
Wt0.DBSYSTEMVALUES_ORACLE = us0;
Wt0.DBSYSTEMVALUES_DB2 = ps0;
Wt0.DBSYSTEMVALUES_POSTGRESQL = cs0;
Wt0.DBSYSTEMVALUES_REDSHIFT = ls0;
Wt0.DBSYSTEMVALUES_HIVE = is0;
Wt0.DBSYSTEMVALUES_CLOUDSCAPE = ns0;
Wt0.DBSYSTEMVALUES_HSQLDB = as0;
Wt0.DBSYSTEMVALUES_PROGRESS = ss0;
Wt0.DBSYSTEMVALUES_MAXDB = rs0;
Wt0.DBSYSTEMVALUES_HANADB = os0;
Wt0.DBSYSTEMVALUES_INGRES = ts0;
Wt0.DBSYSTEMVALUES_FIRSTSQL = es0;
Wt0.DBSYSTEMVALUES_EDB = Ar0;
Wt0.DBSYSTEMVALUES_CACHE = Br0;
Wt0.DBSYSTEMVALUES_ADABAS = Qr0;
Wt0.DBSYSTEMVALUES_FIREBIRD = Ir0;
Wt0.DBSYSTEMVALUES_DERBY = Gr0;
Wt0.DBSYSTEMVALUES_FILEMAKER = Dr0;
Wt0.DBSYSTEMVALUES_INFORMIX = Zr0;
Wt0.DBSYSTEMVALUES_INSTANTDB = Yr0;
Wt0.DBSYSTEMVALUES_INTERBASE = Wr0;
Wt0.DBSYSTEMVALUES_MARIADB = Fr0;
Wt0.DBSYSTEMVALUES_NETEZZA = Jr0;
Wt0.DBSYSTEMVALUES_PERVASIVE = Cr0;
Wt0.DBSYSTEMVALUES_POINTBASE = Xr0;
Wt0.DBSYSTEMVALUES_SQLITE = Vr0;
Wt0.DBSYSTEMVALUES_SYBASE = Kr0;
Wt0.DBSYSTEMVALUES_TERADATA = Hr0;
Wt0.DBSYSTEMVALUES_VERTICA = zr0;
Wt0.DBSYSTEMVALUES_H2 = wr0;
Wt0.DBSYSTEMVALUES_COLDFUSION = Er0;
Wt0.DBSYSTEMVALUES_CASSANDRA = Ur0;
Wt0.DBSYSTEMVALUES_HBASE = Nr0;
Wt0.DBSYSTEMVALUES_MONGODB = $r0;
Wt0.DBSYSTEMVALUES_REDIS = qr0;
Wt0.DBSYSTEMVALUES_COUCHBASE = Mr0;
Wt0.DBSYSTEMVALUES_COUCHDB = Lr0;
Wt0.DBSYSTEMVALUES_COSMOSDB = Rr0;
Wt0.DBSYSTEMVALUES_DYNAMODB = Or0;
Wt0.DBSYSTEMVALUES_NEO4J = Tr0;
Wt0.DBSYSTEMVALUES_GEODE = Pr0;
Wt0.DBSYSTEMVALUES_ELASTICSEARCH = Sr0;
Wt0.DBSYSTEMVALUES_MEMCACHED = _r0;
Wt0.DBSYSTEMVALUES_COCKROACHDB = jr0;
Wt0.DbSystemValues = zC.createConstMap([
  hs0,
  ms0,
  ds0,
  us0,
  ps0,
  cs0,
  ls0,
  is0,
  ns0,
  as0,
  ss0,
  rs0,
  os0,
  ts0,
  es0,
  Ar0,
  Br0,
  Qr0,
  Ir0,
  Gr0,
  Dr0,
  Zr0,
  Yr0,
  Wr0,
  Fr0,
  Jr0,
  Cr0,
  Xr0,
  Vr0,
  Kr0,
  Hr0,
  zr0,
  wr0,
  Er0,
  Ur0,
  Nr0,
  $r0,
  qr0,
  Mr0,
  Lr0,
  Rr0,
  Or0,
  Tr0,
  Pr0,
  Sr0,
  _r0,
  jr0,
]);
var yr0 = 'all',
  kr0 = 'each_quorum',
  xr0 = 'quorum',
  fr0 = 'local_quorum',
  vr0 = 'one',
  br0 = 'two',
  gr0 = 'three',
  hr0 = 'local_one',
  mr0 = 'any',
  dr0 = 'serial',
  ur0 = 'local_serial';
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_ALL = yr0;
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_EACH_QUORUM = kr0;
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_QUORUM = xr0;
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_LOCAL_QUORUM = fr0;
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_ONE = vr0;
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_TWO = br0;
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_THREE = gr0;
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_LOCAL_ONE = hr0;
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_ANY = mr0;
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_SERIAL = dr0;
Wt0.DBCASSANDRACONSISTENCYLEVELVALUES_LOCAL_SERIAL = ur0;
Wt0.DbCassandraConsistencyLevelValues = zC.createConstMap([
  yr0,
  kr0,
  xr0,
  fr0,
  vr0,
  br0,
  gr0,
  hr0,
  mr0,
  dr0,
  ur0,
]);
var pr0 = 'datasource',
  cr0 = 'http',
  lr0 = 'pubsub',
  ir0 = 'timer',
  nr0 = 'other';
Wt0.FAASTRIGGERVALUES_DATASOURCE = pr0;
Wt0.FAASTRIGGERVALUES_HTTP = cr0;
Wt0.FAASTRIGGERVALUES_PUBSUB = lr0;
Wt0.FAASTRIGGERVALUES_TIMER = ir0;
Wt0.FAASTRIGGERVALUES_OTHER = nr0;
Wt0.FaasTriggerValues = zC.createConstMap([pr0, cr0, lr0, ir0, nr0]);
var ar0 = 'insert',
  sr0 = 'edit',
  rr0 = 'delete';
Wt0.FAASDOCUMENTOPERATIONVALUES_INSERT = ar0;
Wt0.FAASDOCUMENTOPERATIONVALUES_EDIT = sr0;
Wt0.FAASDOCUMENTOPERATIONVALUES_DELETE = rr0;
Wt0.FaasDocumentOperationValues = zC.createConstMap([ar0, sr0, rr0]);
var or0 = 'alibaba_cloud',
  tr0 = 'aws',
  er0 = 'azure',
  Ao0 = 'gcp';
Wt0.FAASINVOKEDPROVIDERVALUES_ALIBABA_CLOUD = or0;
Wt0.FAASINVOKEDPROVIDERVALUES_AWS = tr0;
Wt0.FAASINVOKEDPROVIDERVALUES_AZURE = er0;
Wt0.FAASINVOKEDPROVIDERVALUES_GCP = Ao0;
Wt0.FaasInvokedProviderValues = zC.createConstMap([or0, tr0, er0, Ao0]);
var Bo0 = 'ip_tcp',
  Qo0 = 'ip_udp',
  Io0 = 'ip',
  Go0 = 'unix',
  Do0 = 'pipe',
  Zo0 = 'inproc',
  Yo0 = 'other';
Wt0.NETTRANSPORTVALUES_IP_TCP = Bo0;
Wt0.NETTRANSPORTVALUES_IP_UDP = Qo0;
Wt0.NETTRANSPORTVALUES_IP = Io0;
Wt0.NETTRANSPORTVALUES_UNIX = Go0;
Wt0.NETTRANSPORTVALUES_PIPE = Do0;
Wt0.NETTRANSPORTVALUES_INPROC = Zo0;
Wt0.NETTRANSPORTVALUES_OTHER = Yo0;
Wt0.NetTransportValues = zC.createConstMap([Bo0, Qo0, Io0, Go0, Do0, Zo0, Yo0]);
var Wo0 = 'wifi',
  Fo0 = 'wired',
  Jo0 = 'cell',
  Co0 = 'unavailable',
  Xo0 = 'unknown';
Wt0.NETHOSTCONNECTIONTYPEVALUES_WIFI = Wo0;
Wt0.NETHOSTCONNECTIONTYPEVALUES_WIRED = Fo0;
Wt0.NETHOSTCONNECTIONTYPEVALUES_CELL = Jo0;
Wt0.NETHOSTCONNECTIONTYPEVALUES_UNAVAILABLE = Co0;
Wt0.NETHOSTCONNECTIONTYPEVALUES_UNKNOWN = Xo0;
Wt0.NetHostConnectionTypeValues = zC.createConstMap([Wo0, Fo0, Jo0, Co0, Xo0]);
var Vo0 = 'gprs',
  Ko0 = 'edge',
  Ho0 = 'umts',
  zo0 = 'cdma',
  wo0 = 'evdo_0',
  Eo0 = 'evdo_a',
  Uo0 = 'cdma2000_1xrtt',
  No0 = 'hsdpa',
  $o0 = 'hsupa',
  qo0 = 'hspa',
  Mo0 = 'iden',
  Lo0 = 'evdo_b',
  Ro0 = 'lte',
  Oo0 = 'ehrpd',
  To0 = 'hspap',
  Po0 = 'gsm',
  So0 = 'td_scdma',
  _o0 = 'iwlan',
  jo0 = 'nr',
  yo0 = 'nrnsa',
  ko0 = 'lte_ca';
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_GPRS = Vo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_EDGE = Ko0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_UMTS = Ho0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_CDMA = zo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_EVDO_0 = wo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_EVDO_A = Eo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_CDMA2000_1XRTT = Uo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_HSDPA = No0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_HSUPA = $o0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_HSPA = qo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_IDEN = Mo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_EVDO_B = Lo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_LTE = Ro0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_EHRPD = Oo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_HSPAP = To0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_GSM = Po0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_TD_SCDMA = So0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_IWLAN = _o0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_NR = jo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_NRNSA = yo0;
Wt0.NETHOSTCONNECTIONSUBTYPEVALUES_LTE_CA = ko0;
Wt0.NetHostConnectionSubtypeValues = zC.createConstMap([
  Vo0,
  Ko0,
  Ho0,
  zo0,
  wo0,
  Eo0,
  Uo0,
  No0,
  $o0,
  qo0,
  Mo0,
  Lo0,
  Ro0,
  Oo0,
  To0,
  Po0,
  So0,
  _o0,
  jo0,
  yo0,
  ko0,
]);
var xo0 = '1.0',
  fo0 = '1.1',
  vo0 = '2.0',
  bo0 = 'SPDY',
  go0 = 'QUIC';
Wt0.HTTPFLAVORVALUES_HTTP_1_0 = xo0;
Wt0.HTTPFLAVORVALUES_HTTP_1_1 = fo0;
Wt0.HTTPFLAVORVALUES_HTTP_2_0 = vo0;
Wt0.HTTPFLAVORVALUES_SPDY = bo0;
Wt0.HTTPFLAVORVALUES_QUIC = go0;
Wt0.HttpFlavorValues = { HTTP_1_0: xo0, HTTP_1_1: fo0, HTTP_2_0: vo0, SPDY: bo0, QUIC: go0 };
var ho0 = 'queue',
  mo0 = 'topic';
Wt0.MESSAGINGDESTINATIONKINDVALUES_QUEUE = ho0;
Wt0.MESSAGINGDESTINATIONKINDVALUES_TOPIC = mo0;
Wt0.MessagingDestinationKindValues = zC.createConstMap([ho0, mo0]);
var do0 = 'receive',
  uo0 = 'process';
Wt0.MESSAGINGOPERATIONVALUES_RECEIVE = do0;
Wt0.MESSAGINGOPERATIONVALUES_PROCESS = uo0;
Wt0.MessagingOperationValues = zC.createConstMap([do0, uo0]);
var po0 = 0,
  co0 = 1,
  lo0 = 2,
  io0 = 3,
  no0 = 4,
  ao0 = 5,
  so0 = 6,
  ro0 = 7,
  oo0 = 8,
  to0 = 9,
  eo0 = 10,
  At0 = 11,
  Bt0 = 12,
  Qt0 = 13,
  It0 = 14,
  Gt0 = 15,
  Dt0 = 16;
Wt0.RPCGRPCSTATUSCODEVALUES_OK = po0;
Wt0.RPCGRPCSTATUSCODEVALUES_CANCELLED = co0;
Wt0.RPCGRPCSTATUSCODEVALUES_UNKNOWN = lo0;
Wt0.RPCGRPCSTATUSCODEVALUES_INVALID_ARGUMENT = io0;
Wt0.RPCGRPCSTATUSCODEVALUES_DEADLINE_EXCEEDED = no0;
Wt0.RPCGRPCSTATUSCODEVALUES_NOT_FOUND = ao0;
Wt0.RPCGRPCSTATUSCODEVALUES_ALREADY_EXISTS = so0;
Wt0.RPCGRPCSTATUSCODEVALUES_PERMISSION_DENIED = ro0;
Wt0.RPCGRPCSTATUSCODEVALUES_RESOURCE_EXHAUSTED = oo0;
Wt0.RPCGRPCSTATUSCODEVALUES_FAILED_PRECONDITION = to0;
Wt0.RPCGRPCSTATUSCODEVALUES_ABORTED = eo0;
Wt0.RPCGRPCSTATUSCODEVALUES_OUT_OF_RANGE = At0;
Wt0.RPCGRPCSTATUSCODEVALUES_UNIMPLEMENTED = Bt0;
Wt0.RPCGRPCSTATUSCODEVALUES_INTERNAL = Qt0;
Wt0.RPCGRPCSTATUSCODEVALUES_UNAVAILABLE = It0;
Wt0.RPCGRPCSTATUSCODEVALUES_DATA_LOSS = Gt0;
Wt0.RPCGRPCSTATUSCODEVALUES_UNAUTHENTICATED = Dt0;
Wt0.RpcGrpcStatusCodeValues = {
  OK: po0,
  CANCELLED: co0,
  UNKNOWN: lo0,
  INVALID_ARGUMENT: io0,
  DEADLINE_EXCEEDED: no0,
  NOT_FOUND: ao0,
  ALREADY_EXISTS: so0,
  PERMISSION_DENIED: ro0,
  RESOURCE_EXHAUSTED: oo0,
  FAILED_PRECONDITION: to0,
  ABORTED: eo0,
  OUT_OF_RANGE: At0,
  UNIMPLEMENTED: Bt0,
  INTERNAL: Qt0,
  UNAVAILABLE: It0,
  DATA_LOSS: Gt0,
  UNAUTHENTICATED: Dt0,
};
var Zt0 = 'SENT',
  Yt0 = 'RECEIVED';
Wt0.MESSAGETYPEVALUES_SENT = Zt0;
Wt0.MESSAGETYPEVALUES_RECEIVED = Yt0;
Wt0.MessageTypeValues = zC.createConstMap([Zt0, Yt0]);
