// Module: l12
// Params: d12

Object.defineProperty(d12, '__esModule', { value: !0 });
d12.SEMRESATTRS_K8S_STATEFULSET_NAME =
  d12.SEMRESATTRS_K8S_STATEFULSET_UID =
  d12.SEMRESATTRS_K8S_DEPLOYMENT_NAME =
  d12.SEMRESATTRS_K8S_DEPLOYMENT_UID =
  d12.SEMRESATTRS_K8S_REPLICASET_NAME =
  d12.SEMRESATTRS_K8S_REPLICASET_UID =
  d12.SEMRESATTRS_K8S_CONTAINER_NAME =
  d12.SEMRESATTRS_K8S_POD_NAME =
  d12.SEMRESATTRS_K8S_POD_UID =
  d12.SEMRESATTRS_K8S_NAMESPACE_NAME =
  d12.SEMRESATTRS_K8S_NODE_UID =
  d12.SEMRESATTRS_K8S_NODE_NAME =
  d12.SEMRESATTRS_K8S_CLUSTER_NAME =
  d12.SEMRESATTRS_HOST_IMAGE_VERSION =
  d12.SEMRESATTRS_HOST_IMAGE_ID =
  d12.SEMRESATTRS_HOST_IMAGE_NAME =
  d12.SEMRESATTRS_HOST_ARCH =
  d12.SEMRESATTRS_HOST_TYPE =
  d12.SEMRESATTRS_HOST_NAME =
  d12.SEMRESATTRS_HOST_ID =
  d12.SEMRESATTRS_FAAS_MAX_MEMORY =
  d12.SEMRESATTRS_FAAS_INSTANCE =
  d12.SEMRESATTRS_FAAS_VERSION =
  d12.SEMRESATTRS_FAAS_ID =
  d12.SEMRESATTRS_FAAS_NAME =
  d12.SEMRESATTRS_DEVICE_MODEL_NAME =
  d12.SEMRESATTRS_DEVICE_MODEL_IDENTIFIER =
  d12.SEMRESATTRS_DEVICE_ID =
  d12.SEMRESATTRS_DEPLOYMENT_ENVIRONMENT =
  d12.SEMRESATTRS_CONTAINER_IMAGE_TAG =
  d12.SEMRESATTRS_CONTAINER_IMAGE_NAME =
  d12.SEMRESATTRS_CONTAINER_RUNTIME =
  d12.SEMRESATTRS_CONTAINER_ID =
  d12.SEMRESATTRS_CONTAINER_NAME =
  d12.SEMRESATTRS_AWS_LOG_STREAM_ARNS =
  d12.SEMRESATTRS_AWS_LOG_STREAM_NAMES =
  d12.SEMRESATTRS_AWS_LOG_GROUP_ARNS =
  d12.SEMRESATTRS_AWS_LOG_GROUP_NAMES =
  d12.SEMRESATTRS_AWS_EKS_CLUSTER_ARN =
  d12.SEMRESATTRS_AWS_ECS_TASK_REVISION =
  d12.SEMRESATTRS_AWS_ECS_TASK_FAMILY =
  d12.SEMRESATTRS_AWS_ECS_TASK_ARN =
  d12.SEMRESATTRS_AWS_ECS_LAUNCHTYPE =
  d12.SEMRESATTRS_AWS_ECS_CLUSTER_ARN =
  d12.SEMRESATTRS_AWS_ECS_CONTAINER_ARN =
  d12.SEMRESATTRS_CLOUD_PLATFORM =
  d12.SEMRESATTRS_CLOUD_AVAILABILITY_ZONE =
  d12.SEMRESATTRS_CLOUD_REGION =
  d12.SEMRESATTRS_CLOUD_ACCOUNT_ID =
  d12.SEMRESATTRS_CLOUD_PROVIDER =
    void 0;
d12.CLOUDPLATFORMVALUES_GCP_COMPUTE_ENGINE =
  d12.CLOUDPLATFORMVALUES_AZURE_APP_SERVICE =
  d12.CLOUDPLATFORMVALUES_AZURE_FUNCTIONS =
  d12.CLOUDPLATFORMVALUES_AZURE_AKS =
  d12.CLOUDPLATFORMVALUES_AZURE_CONTAINER_INSTANCES =
  d12.CLOUDPLATFORMVALUES_AZURE_VM =
  d12.CLOUDPLATFORMVALUES_AWS_ELASTIC_BEANSTALK =
  d12.CLOUDPLATFORMVALUES_AWS_LAMBDA =
  d12.CLOUDPLATFORMVALUES_AWS_EKS =
  d12.CLOUDPLATFORMVALUES_AWS_ECS =
  d12.CLOUDPLATFORMVALUES_AWS_EC2 =
  d12.CLOUDPLATFORMVALUES_ALIBABA_CLOUD_FC =
  d12.CLOUDPLATFORMVALUES_ALIBABA_CLOUD_ECS =
  d12.CloudProviderValues =
  d12.CLOUDPROVIDERVALUES_GCP =
  d12.CLOUDPROVIDERVALUES_AZURE =
  d12.CLOUDPROVIDERVALUES_AWS =
  d12.CLOUDPROVIDERVALUES_ALIBABA_CLOUD =
  d12.SemanticResourceAttributes =
  d12.SEMRESATTRS_WEBENGINE_DESCRIPTION =
  d12.SEMRESATTRS_WEBENGINE_VERSION =
  d12.SEMRESATTRS_WEBENGINE_NAME =
  d12.SEMRESATTRS_TELEMETRY_AUTO_VERSION =
  d12.SEMRESATTRS_TELEMETRY_SDK_VERSION =
  d12.SEMRESATTRS_TELEMETRY_SDK_LANGUAGE =
  d12.SEMRESATTRS_TELEMETRY_SDK_NAME =
  d12.SEMRESATTRS_SERVICE_VERSION =
  d12.SEMRESATTRS_SERVICE_INSTANCE_ID =
  d12.SEMRESATTRS_SERVICE_NAMESPACE =
  d12.SEMRESATTRS_SERVICE_NAME =
  d12.SEMRESATTRS_PROCESS_RUNTIME_DESCRIPTION =
  d12.SEMRESATTRS_PROCESS_RUNTIME_VERSION =
  d12.SEMRESATTRS_PROCESS_RUNTIME_NAME =
  d12.SEMRESATTRS_PROCESS_OWNER =
  d12.SEMRESATTRS_PROCESS_COMMAND_ARGS =
  d12.SEMRESATTRS_PROCESS_COMMAND_LINE =
  d12.SEMRESATTRS_PROCESS_COMMAND =
  d12.SEMRESATTRS_PROCESS_EXECUTABLE_PATH =
  d12.SEMRESATTRS_PROCESS_EXECUTABLE_NAME =
  d12.SEMRESATTRS_PROCESS_PID =
  d12.SEMRESATTRS_OS_VERSION =
  d12.SEMRESATTRS_OS_NAME =
  d12.SEMRESATTRS_OS_DESCRIPTION =
  d12.SEMRESATTRS_OS_TYPE =
  d12.SEMRESATTRS_K8S_CRONJOB_NAME =
  d12.SEMRESATTRS_K8S_CRONJOB_UID =
  d12.SEMRESATTRS_K8S_JOB_NAME =
  d12.SEMRESATTRS_K8S_JOB_UID =
  d12.SEMRESATTRS_K8S_DAEMONSET_NAME =
  d12.SEMRESATTRS_K8S_DAEMONSET_UID =
    void 0;
d12.TelemetrySdkLanguageValues =
  d12.TELEMETRYSDKLANGUAGEVALUES_WEBJS =
  d12.TELEMETRYSDKLANGUAGEVALUES_RUBY =
  d12.TELEMETRYSDKLANGUAGEVALUES_PYTHON =
  d12.TELEMETRYSDKLANGUAGEVALUES_PHP =
  d12.TELEMETRYSDKLANGUAGEVALUES_NODEJS =
  d12.TELEMETRYSDKLANGUAGEVALUES_JAVA =
  d12.TELEMETRYSDKLANGUAGEVALUES_GO =
  d12.TELEMETRYSDKLANGUAGEVALUES_ERLANG =
  d12.TELEMETRYSDKLANGUAGEVALUES_DOTNET =
  d12.TELEMETRYSDKLANGUAGEVALUES_CPP =
  d12.OsTypeValues =
  d12.OSTYPEVALUES_Z_OS =
  d12.OSTYPEVALUES_SOLARIS =
  d12.OSTYPEVALUES_AIX =
  d12.OSTYPEVALUES_HPUX =
  d12.OSTYPEVALUES_DRAGONFLYBSD =
  d12.OSTYPEVALUES_OPENBSD =
  d12.OSTYPEVALUES_NETBSD =
  d12.OSTYPEVALUES_FREEBSD =
  d12.OSTYPEVALUES_DARWIN =
  d12.OSTYPEVALUES_LINUX =
  d12.OSTYPEVALUES_WINDOWS =
  d12.HostArchValues =
  d12.HOSTARCHVALUES_X86 =
  d12.HOSTARCHVALUES_PPC64 =
  d12.HOSTARCHVALUES_PPC32 =
  d12.HOSTARCHVALUES_IA64 =
  d12.HOSTARCHVALUES_ARM64 =
  d12.HOSTARCHVALUES_ARM32 =
  d12.HOSTARCHVALUES_AMD64 =
  d12.AwsEcsLaunchtypeValues =
  d12.AWSECSLAUNCHTYPEVALUES_FARGATE =
  d12.AWSECSLAUNCHTYPEVALUES_EC2 =
  d12.CloudPlatformValues =
  d12.CLOUDPLATFORMVALUES_GCP_APP_ENGINE =
  d12.CLOUDPLATFORMVALUES_GCP_CLOUD_FUNCTIONS =
  d12.CLOUDPLATFORMVALUES_GCP_KUBERNETES_ENGINE =
  d12.CLOUDPLATFORMVALUES_GCP_CLOUD_RUN =
    void 0;
var K_ = Mc1(),
  wt0 = 'cloud.provider',
  Et0 = 'cloud.account.id',
  Ut0 = 'cloud.region',
  Nt0 = 'cloud.availability_zone',
  $t0 = 'cloud.platform',
  qt0 = 'aws.ecs.container.arn',
  Mt0 = 'aws.ecs.cluster.arn',
  Lt0 = 'aws.ecs.launchtype',
  Rt0 = 'aws.ecs.task.arn',
  Ot0 = 'aws.ecs.task.family',
  Tt0 = 'aws.ecs.task.revision',
  Pt0 = 'aws.eks.cluster.arn',
  St0 = 'aws.log.group.names',
  _t0 = 'aws.log.group.arns',
  jt0 = 'aws.log.stream.names',
  yt0 = 'aws.log.stream.arns',
  kt0 = 'container.name',
  xt0 = 'container.id',
  ft0 = 'container.runtime',
  vt0 = 'container.image.name',
  bt0 = 'container.image.tag',
  gt0 = 'deployment.environment',
  ht0 = 'device.id',
  mt0 = 'device.model.identifier',
  dt0 = 'device.model.name',
  ut0 = 'faas.name',
  pt0 = 'faas.id',
  ct0 = 'faas.version',
  lt0 = 'faas.instance',
  it0 = 'faas.max_memory',
  nt0 = 'host.id',
  at0 = 'host.name',
  st0 = 'host.type',
  rt0 = 'host.arch',
  ot0 = 'host.image.name',
  tt0 = 'host.image.id',
  et0 = 'host.image.version',
  Ae0 = 'k8s.cluster.name',
  Be0 = 'k8s.node.name',
  Qe0 = 'k8s.node.uid',
  Ie0 = 'k8s.namespace.name',
  Ge0 = 'k8s.pod.uid',
  De0 = 'k8s.pod.name',
  Ze0 = 'k8s.container.name',
  Ye0 = 'k8s.replicaset.uid',
  We0 = 'k8s.replicaset.name',
  Fe0 = 'k8s.deployment.uid',
  Je0 = 'k8s.deployment.name',
  Ce0 = 'k8s.statefulset.uid',
  Xe0 = 'k8s.statefulset.name',
  Ve0 = 'k8s.daemonset.uid',
  Ke0 = 'k8s.daemonset.name',
  He0 = 'k8s.job.uid',
  ze0 = 'k8s.job.name',
  we0 = 'k8s.cronjob.uid',
  Ee0 = 'k8s.cronjob.name',
  Ue0 = 'os.type',
  Ne0 = 'os.description',
  $e0 = 'os.name',
  qe0 = 'os.version',
  Me0 = 'process.pid',
  Le0 = 'process.executable.name',
  Re0 = 'process.executable.path',
  Oe0 = 'process.command',
  Te0 = 'process.command_line',
  Pe0 = 'process.command_args',
  Se0 = 'process.owner',
  _e0 = 'process.runtime.name',
  je0 = 'process.runtime.version',
  ye0 = 'process.runtime.description',
  ke0 = 'service.name',
  xe0 = 'service.namespace',
  fe0 = 'service.instance.id',
  ve0 = 'service.version',
  be0 = 'telemetry.sdk.name',
  ge0 = 'telemetry.sdk.language',
  he0 = 'telemetry.sdk.version',
  me0 = 'telemetry.auto.version',
  de0 = 'webengine.name',
  ue0 = 'webengine.version',
  pe0 = 'webengine.description';
d12.SEMRESATTRS_CLOUD_PROVIDER = wt0;
d12.SEMRESATTRS_CLOUD_ACCOUNT_ID = Et0;
d12.SEMRESATTRS_CLOUD_REGION = Ut0;
d12.SEMRESATTRS_CLOUD_AVAILABILITY_ZONE = Nt0;
d12.SEMRESATTRS_CLOUD_PLATFORM = $t0;
d12.SEMRESATTRS_AWS_ECS_CONTAINER_ARN = qt0;
d12.SEMRESATTRS_AWS_ECS_CLUSTER_ARN = Mt0;
d12.SEMRESATTRS_AWS_ECS_LAUNCHTYPE = Lt0;
d12.SEMRESATTRS_AWS_ECS_TASK_ARN = Rt0;
d12.SEMRESATTRS_AWS_ECS_TASK_FAMILY = Ot0;
d12.SEMRESATTRS_AWS_ECS_TASK_REVISION = Tt0;
d12.SEMRESATTRS_AWS_EKS_CLUSTER_ARN = Pt0;
d12.SEMRESATTRS_AWS_LOG_GROUP_NAMES = St0;
d12.SEMRESATTRS_AWS_LOG_GROUP_ARNS = _t0;
d12.SEMRESATTRS_AWS_LOG_STREAM_NAMES = jt0;
d12.SEMRESATTRS_AWS_LOG_STREAM_ARNS = yt0;
d12.SEMRESATTRS_CONTAINER_NAME = kt0;
d12.SEMRESATTRS_CONTAINER_ID = xt0;
d12.SEMRESATTRS_CONTAINER_RUNTIME = ft0;
d12.SEMRESATTRS_CONTAINER_IMAGE_NAME = vt0;
d12.SEMRESATTRS_CONTAINER_IMAGE_TAG = bt0;
d12.SEMRESATTRS_DEPLOYMENT_ENVIRONMENT = gt0;
d12.SEMRESATTRS_DEVICE_ID = ht0;
d12.SEMRESATTRS_DEVICE_MODEL_IDENTIFIER = mt0;
d12.SEMRESATTRS_DEVICE_MODEL_NAME = dt0;
d12.SEMRESATTRS_FAAS_NAME = ut0;
d12.SEMRESATTRS_FAAS_ID = pt0;
d12.SEMRESATTRS_FAAS_VERSION = ct0;
d12.SEMRESATTRS_FAAS_INSTANCE = lt0;
d12.SEMRESATTRS_FAAS_MAX_MEMORY = it0;
d12.SEMRESATTRS_HOST_ID = nt0;
d12.SEMRESATTRS_HOST_NAME = at0;
d12.SEMRESATTRS_HOST_TYPE = st0;
d12.SEMRESATTRS_HOST_ARCH = rt0;
d12.SEMRESATTRS_HOST_IMAGE_NAME = ot0;
d12.SEMRESATTRS_HOST_IMAGE_ID = tt0;
d12.SEMRESATTRS_HOST_IMAGE_VERSION = et0;
d12.SEMRESATTRS_K8S_CLUSTER_NAME = Ae0;
d12.SEMRESATTRS_K8S_NODE_NAME = Be0;
d12.SEMRESATTRS_K8S_NODE_UID = Qe0;
d12.SEMRESATTRS_K8S_NAMESPACE_NAME = Ie0;
d12.SEMRESATTRS_K8S_POD_UID = Ge0;
d12.SEMRESATTRS_K8S_POD_NAME = De0;
d12.SEMRESATTRS_K8S_CONTAINER_NAME = Ze0;
d12.SEMRESATTRS_K8S_REPLICASET_UID = Ye0;
d12.SEMRESATTRS_K8S_REPLICASET_NAME = We0;
d12.SEMRESATTRS_K8S_DEPLOYMENT_UID = Fe0;
d12.SEMRESATTRS_K8S_DEPLOYMENT_NAME = Je0;
d12.SEMRESATTRS_K8S_STATEFULSET_UID = Ce0;
d12.SEMRESATTRS_K8S_STATEFULSET_NAME = Xe0;
d12.SEMRESATTRS_K8S_DAEMONSET_UID = Ve0;
d12.SEMRESATTRS_K8S_DAEMONSET_NAME = Ke0;
d12.SEMRESATTRS_K8S_JOB_UID = He0;
d12.SEMRESATTRS_K8S_JOB_NAME = ze0;
d12.SEMRESATTRS_K8S_CRONJOB_UID = we0;
d12.SEMRESATTRS_K8S_CRONJOB_NAME = Ee0;
d12.SEMRESATTRS_OS_TYPE = Ue0;
d12.SEMRESATTRS_OS_DESCRIPTION = Ne0;
d12.SEMRESATTRS_OS_NAME = $e0;
d12.SEMRESATTRS_OS_VERSION = qe0;
d12.SEMRESATTRS_PROCESS_PID = Me0;
d12.SEMRESATTRS_PROCESS_EXECUTABLE_NAME = Le0;
d12.SEMRESATTRS_PROCESS_EXECUTABLE_PATH = Re0;
d12.SEMRESATTRS_PROCESS_COMMAND = Oe0;
d12.SEMRESATTRS_PROCESS_COMMAND_LINE = Te0;
d12.SEMRESATTRS_PROCESS_COMMAND_ARGS = Pe0;
d12.SEMRESATTRS_PROCESS_OWNER = Se0;
d12.SEMRESATTRS_PROCESS_RUNTIME_NAME = _e0;
d12.SEMRESATTRS_PROCESS_RUNTIME_VERSION = je0;
d12.SEMRESATTRS_PROCESS_RUNTIME_DESCRIPTION = ye0;
d12.SEMRESATTRS_SERVICE_NAME = ke0;
d12.SEMRESATTRS_SERVICE_NAMESPACE = xe0;
d12.SEMRESATTRS_SERVICE_INSTANCE_ID = fe0;
d12.SEMRESATTRS_SERVICE_VERSION = ve0;
d12.SEMRESATTRS_TELEMETRY_SDK_NAME = be0;
d12.SEMRESATTRS_TELEMETRY_SDK_LANGUAGE = ge0;
d12.SEMRESATTRS_TELEMETRY_SDK_VERSION = he0;
d12.SEMRESATTRS_TELEMETRY_AUTO_VERSION = me0;
d12.SEMRESATTRS_WEBENGINE_NAME = de0;
d12.SEMRESATTRS_WEBENGINE_VERSION = ue0;
d12.SEMRESATTRS_WEBENGINE_DESCRIPTION = pe0;
d12.SemanticResourceAttributes = K_.createConstMap([
  wt0,
  Et0,
  Ut0,
  Nt0,
  $t0,
  qt0,
  Mt0,
  Lt0,
  Rt0,
  Ot0,
  Tt0,
  Pt0,
  St0,
  _t0,
  jt0,
  yt0,
  kt0,
  xt0,
  ft0,
  vt0,
  bt0,
  gt0,
  ht0,
  mt0,
  dt0,
  ut0,
  pt0,
  ct0,
  lt0,
  it0,
  nt0,
  at0,
  st0,
  rt0,
  ot0,
  tt0,
  et0,
  Ae0,
  Be0,
  Qe0,
  Ie0,
  Ge0,
  De0,
  Ze0,
  Ye0,
  We0,
  Fe0,
  Je0,
  Ce0,
  Xe0,
  Ve0,
  Ke0,
  He0,
  ze0,
  we0,
  Ee0,
  Ue0,
  Ne0,
  $e0,
  qe0,
  Me0,
  Le0,
  Re0,
  Oe0,
  Te0,
  Pe0,
  Se0,
  _e0,
  je0,
  ye0,
  ke0,
  xe0,
  fe0,
  ve0,
  be0,
  ge0,
  he0,
  me0,
  de0,
  ue0,
  pe0,
]);
var ce0 = 'alibaba_cloud',
  le0 = 'aws',
  ie0 = 'azure',
  ne0 = 'gcp';
d12.CLOUDPROVIDERVALUES_ALIBABA_CLOUD = ce0;
d12.CLOUDPROVIDERVALUES_AWS = le0;
d12.CLOUDPROVIDERVALUES_AZURE = ie0;
d12.CLOUDPROVIDERVALUES_GCP = ne0;
d12.CloudProviderValues = K_.createConstMap([ce0, le0, ie0, ne0]);
var ae0 = 'alibaba_cloud_ecs',
  se0 = 'alibaba_cloud_fc',
  re0 = 'aws_ec2',
  oe0 = 'aws_ecs',
  te0 = 'aws_eks',
  ee0 = 'aws_lambda',
  A12 = 'aws_elastic_beanstalk',
  B12 = 'azure_vm',
  Q12 = 'azure_container_instances',
  I12 = 'azure_aks',
  G12 = 'azure_functions',
  D12 = 'azure_app_service',
  Z12 = 'gcp_compute_engine',
  Y12 = 'gcp_cloud_run',
  W12 = 'gcp_kubernetes_engine',
  F12 = 'gcp_cloud_functions',
  J12 = 'gcp_app_engine';
d12.CLOUDPLATFORMVALUES_ALIBABA_CLOUD_ECS = ae0;
d12.CLOUDPLATFORMVALUES_ALIBABA_CLOUD_FC = se0;
d12.CLOUDPLATFORMVALUES_AWS_EC2 = re0;
d12.CLOUDPLATFORMVALUES_AWS_ECS = oe0;
d12.CLOUDPLATFORMVALUES_AWS_EKS = te0;
d12.CLOUDPLATFORMVALUES_AWS_LAMBDA = ee0;
d12.CLOUDPLATFORMVALUES_AWS_ELASTIC_BEANSTALK = A12;
d12.CLOUDPLATFORMVALUES_AZURE_VM = B12;
d12.CLOUDPLATFORMVALUES_AZURE_CONTAINER_INSTANCES = Q12;
d12.CLOUDPLATFORMVALUES_AZURE_AKS = I12;
d12.CLOUDPLATFORMVALUES_AZURE_FUNCTIONS = G12;
d12.CLOUDPLATFORMVALUES_AZURE_APP_SERVICE = D12;
d12.CLOUDPLATFORMVALUES_GCP_COMPUTE_ENGINE = Z12;
d12.CLOUDPLATFORMVALUES_GCP_CLOUD_RUN = Y12;
d12.CLOUDPLATFORMVALUES_GCP_KUBERNETES_ENGINE = W12;
d12.CLOUDPLATFORMVALUES_GCP_CLOUD_FUNCTIONS = F12;
d12.CLOUDPLATFORMVALUES_GCP_APP_ENGINE = J12;
d12.CloudPlatformValues = K_.createConstMap([
  ae0,
  se0,
  re0,
  oe0,
  te0,
  ee0,
  A12,
  B12,
  Q12,
  I12,
  G12,
  D12,
  Z12,
  Y12,
  W12,
  F12,
  J12,
]);
var C12 = 'ec2',
  X12 = 'fargate';
d12.AWSECSLAUNCHTYPEVALUES_EC2 = C12;
d12.AWSECSLAUNCHTYPEVALUES_FARGATE = X12;
d12.AwsEcsLaunchtypeValues = K_.createConstMap([C12, X12]);
var V12 = 'amd64',
  K12 = 'arm32',
  H12 = 'arm64',
  z12 = 'ia64',
  w12 = 'ppc32',
  E12 = 'ppc64',
  U12 = 'x86';
d12.HOSTARCHVALUES_AMD64 = V12;
d12.HOSTARCHVALUES_ARM32 = K12;
d12.HOSTARCHVALUES_ARM64 = H12;
d12.HOSTARCHVALUES_IA64 = z12;
d12.HOSTARCHVALUES_PPC32 = w12;
d12.HOSTARCHVALUES_PPC64 = E12;
d12.HOSTARCHVALUES_X86 = U12;
d12.HostArchValues = K_.createConstMap([V12, K12, H12, z12, w12, E12, U12]);
var N12 = 'windows',
  $12 = 'linux',
  q12 = 'darwin',
  M12 = 'freebsd',
  L12 = 'netbsd',
  R12 = 'openbsd',
  O12 = 'dragonflybsd',
  T12 = 'hpux',
  P12 = 'aix',
  S12 = 'solaris',
  _12 = 'z_os';
d12.OSTYPEVALUES_WINDOWS = N12;
d12.OSTYPEVALUES_LINUX = $12;
d12.OSTYPEVALUES_DARWIN = q12;
d12.OSTYPEVALUES_FREEBSD = M12;
d12.OSTYPEVALUES_NETBSD = L12;
d12.OSTYPEVALUES_OPENBSD = R12;
d12.OSTYPEVALUES_DRAGONFLYBSD = O12;
d12.OSTYPEVALUES_HPUX = T12;
d12.OSTYPEVALUES_AIX = P12;
d12.OSTYPEVALUES_SOLARIS = S12;
d12.OSTYPEVALUES_Z_OS = _12;
d12.OsTypeValues = K_.createConstMap([N12, $12, q12, M12, L12, R12, O12, T12, P12, S12, _12]);
var j12 = 'cpp',
  y12 = 'dotnet',
  k12 = 'erlang',
  x12 = 'go',
  f12 = 'java',
  v12 = 'nodejs',
  b12 = 'php',
  g12 = 'python',
  h12 = 'ruby',
  m12 = 'webjs';
d12.TELEMETRYSDKLANGUAGEVALUES_CPP = j12;
d12.TELEMETRYSDKLANGUAGEVALUES_DOTNET = y12;
d12.TELEMETRYSDKLANGUAGEVALUES_ERLANG = k12;
d12.TELEMETRYSDKLANGUAGEVALUES_GO = x12;
d12.TELEMETRYSDKLANGUAGEVALUES_JAVA = f12;
d12.TELEMETRYSDKLANGUAGEVALUES_NODEJS = v12;
d12.TELEMETRYSDKLANGUAGEVALUES_PHP = b12;
d12.TELEMETRYSDKLANGUAGEVALUES_PYTHON = g12;
d12.TELEMETRYSDKLANGUAGEVALUES_RUBY = h12;
d12.TELEMETRYSDKLANGUAGEVALUES_WEBJS = m12;
d12.TelemetrySdkLanguageValues = K_.createConstMap([
  j12,
  y12,
  k12,
  x12,
  f12,
  v12,
  b12,
  g12,
  h12,
  m12,
]);
